/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Computer = React.memo(function Computer(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/computer.glb");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y =
      -1 + Math.sin(state.clock.elapsedTime) * 0.15;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      position={[1.2, 0, 0]}
        scale={[0.5,0.5,0.5]}
        rotation={[0, -1.5, 0]}
     >
       
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_119_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_125_Material066_0.geometry}
        material={materials['Material.074_35']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_127_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_221_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_257_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_259_Material060_0.geometry}
        material={materials['Material.074_34']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_261_Material060_0.geometry}
        material={materials['Material.074_34']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_263_Material060_0.geometry}
        material={materials['Material.074_34']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_420_Tasten_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_426_Tasten_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_784_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_794_Material070_0.geometry}
        material={materials['Material.074_39']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_974_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_976_Material070_0.geometry}
        material={materials['Material.074_39']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_980_Tasten_2_0.geometry}
        material={materials.Tasten_2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_1000_Material070_0.geometry}
        material={materials['Material.074_39']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bg2_bg2_0.geometry}
        material={materials['Material.074_29']}
        position={[-1.537, 1.949, 0.83]}
        rotation={[1.572, -1.442, 1.567]}
        scale={1.13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Color-PewDiePie-Logo_Color-PewDiePie-Logo_0'].geometry}
        material={materials['Material.074_27']}
        position={[1.295, 0.466, -0.275]}
        rotation={[-Math.PI / 2, 0.284, Math.PI / 2]}
        scale={0.124}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_Material055_0.geometry}
        material={materials.PaletteMaterial001}
        position={[-1.386, 2.957, 3.004]}
        rotation={[-Math.PI / 2, -0.07, Math.PI / 2]}
        scale={[3.253, 0.041, 1.841]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004_Material002_0.geometry}
        material={materials['Material.002']}
        position={[-1.487, 1.81, 2.992]}
        rotation={[-Math.PI / 2, -0.07, Math.PI / 2]}
        scale={[1.676, 0.178, 1.935]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube063_Material074_0.geometry}
        material={materials['Material.074_25']}
        position={[1.114, 0.325, -0.274]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[-0.429, 0.429, 0.229]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube073_Material079_0.geometry}
        material={materials['Material.074_6']}
        position={[1.114, 0.324, -0.274]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[-0.429, 0.429, 0.229]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gallerymodel_gallerymodel_0.geometry}
        material={materials['Material.074_28']}
        position={[-1.42, 1.648, 5.961]}
        rotation={[0.441, -1.284, 0.441]}
        scale={0.807}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MY_SCREEN_MY_SCREEN_0.geometry}
        material={materials['Material.074_30']}
        position={[-1.362, 3.001, 3.004]}
        rotation={[-Math.PI / 2, 1.501, Math.PI / 2]}
        scale={[3.316, 3.481, 3.316]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_101_Material067_0.geometry}
        material={materials['Material.074_36']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_103_Material070_0.geometry}
        material={materials['Material.074_39']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_105_Tasten_2_0.geometry}
        material={materials.Tasten_2}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_109_Material069_0.geometry}
        material={materials['Material.074_38']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_113_Material068_0.geometry}
        material={materials['Material.074_37']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_115_Material057_0.geometry}
        material={materials['Material.074_33']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_121_Material066_0.geometry}
        material={materials['Material.074_35']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_131_Material060_0.geometry}
        material={materials['Material.074_34']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_137_Material005_0.geometry}
        material={materials['Material.074_32']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Object_782_OnTheFly-bg_0'].geometry}
        material={materials['Material.074_40']}
        position={[1.016, 0.406, 2.44]}
        rotation={[-Math.PI / 2, 0.078, Math.PI / 2]}
        scale={0.219}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_Material053_0.geometry}
        material={materials['Material.074_21']}
        position={[1.172, 0.256, -0.292]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.244, 1.541, 1.199]}
      />   
    </group>
  );
});

export default Computer;
useGLTF.preload("/models/computer.glb");
