/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Wizard = React.memo(function Wizard(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/computer.glb");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      position={[0, 0, 0]}
      scale={[0.3, 0.3, 0.3]}
      rotation={[0, -1.5, 0]}
    >
    <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.aorus_case_fans_aorus_case_fans_0.geometry}
        material={materials['Material.074_0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013_Material015_0.geometry}
        material={materials['Material.074']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016_Material017_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028_Material026_0.geometry}
        material={materials['Material.074_7']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030_Material026_0.geometry}
        material={materials['Material.074_7']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031_Material008_0.geometry}
        material={materials['Material.074_6']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033_Material025_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043_Material012_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube070_Material100_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014_Material095_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['gigabyte-logo_gigabyte-logo_0'].geometry}
        material={materials['Material.074_31']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['metal-mesh-500x500_metal-mesh-500x500_0'].geometry}
        material={materials['Material.074_5']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_119_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_125_Material066_0.geometry}
        material={materials['Material.074_35']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_127_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_221_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_257_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_259_Material060_0.geometry}
        material={materials['Material.074_34']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_261_Material060_0.geometry}
        material={materials['Material.074_34']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_263_Material060_0.geometry}
        material={materials['Material.074_34']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_420_Tasten_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_426_Tasten_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_784_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_794_Material070_0.geometry}
        material={materials['Material.074_39']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_Material019_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_974_Material057_0.geometry}
        material={materials['Material.074_33']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_976_Material070_0.geometry}
        material={materials['Material.074_39']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_980_Tasten_2_0.geometry}
        material={materials.Tasten_2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_1000_Material070_0.geometry}
        material={materials['Material.074_39']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.usb_usb_0.geometry}
        material={materials['Material.074_14']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.aorus_logotranspa_aorus_logotranspa_0.geometry}
        material={materials['Material.074_24']}
        position={[-1.824, 1.817, -3.158]}
        scale={[0.086, 0.086, 0.091]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bg2_bg2_0.geometry}
        material={materials['Material.074_29']}
        position={[-1.537, 1.949, 0.83]}
        rotation={[1.572, -1.442, 1.567]}
        scale={1.13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Color-PewDiePie-Logo_Color-PewDiePie-Logo_0'].geometry}
        material={materials['Material.074_27']}
        position={[1.295, 0.466, -0.275]}
        rotation={[-Math.PI / 2, 0.284, Math.PI / 2]}
        scale={0.124}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Material_0.geometry}
        material={materials['Material.001']}
        position={[-0.61, -0.006, 1.561]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[-3.689, 7.316, 0.26]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004_Material002_0.geometry}
        material={materials['Material.002']}
        position={[-1.487, 1.81, 2.992]}
        rotation={[-Math.PI / 2, -0.07, Math.PI / 2]}
        scale={[1.676, 0.178, 1.935]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011_Material010_0.geometry}
        material={materials['Material.074']}
        position={[-0.859, 1.997, -3.537]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.735, 0.9, 1.573]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015_Material016_0.geometry}
        material={materials['Material.074_1']}
        position={[-1.655, 2.241, -4.408]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[-0.894, 0.007, 1.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020_Material020_0.geometry}
        material={materials['Material.074_2']}
        position={[-0.961, 0.788, -3.634]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.607, 0.739, 0.343]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025_Material023_0.geometry}
        material={materials['Material.023']}
        position={[-1.655, 2.241, -4.408]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[-0.894, 0.007, 1.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026_Material024_0.geometry}
        material={materials['Material.024']}
        position={[-1.655, 2.241, -4.408]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[-0.894, 0.007, 1.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027_Material008_0.geometry}
        material={materials['Material.074_6']}
        position={[-0.964, 2.71, -4.309]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.015, 0.109, 0.443]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045_Material027_0.geometry}
        material={materials['Material.074_8']}
        position={[-2.121, 0.794, -2.982]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.355, 0.052, 0.206]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048_Material035_0.geometry}
        material={materials['Material.074_15']}
        position={[-1.614, 2.682, -3.682]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.174, 0.394, 0.401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube049_Material040_0.geometry}
        material={materials['Material.074_16']}
        position={[-1.614, 2.682, -3.682]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.174, 0.394, 0.401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube057_Material059_0.geometry}
        material={materials['Material.074_22']}
        position={[-1.272, 2.001, -3.706]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.281, 0.524, 0.127]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058_Material063_0.geometry}
        material={materials['Material.074_23']}
        position={[-1.226, 2.137, -3.704]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.333, 0.545, 0.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube063_Material074_0.geometry}
        material={materials['Material.074_25']}
        position={[1.114, 0.325, -0.274]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[-0.429, 0.429, 0.229]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube075_Material086_0.geometry}
        material={materials['Material.074_26']}
        position={[-2.58, 1.955, -3.715]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.012, 0.524, 0.177]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_Material028_0.geometry}
        material={materials['Material.074_11']}
        position={[-1.692, 1.144, -0.716]}
        rotation={[-1.571, 1.554, 0]}
        scale={[0.194, 0.194, 0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005_Material041_0.geometry}
        material={materials['Material.074_17']}
        position={[-1.611, 2.687, -3.69]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.327, 0.327, 0.342]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006_Material050_0.geometry}
        material={materials['Material.074_19']}
        position={[-2.095, 1.846, -3.701]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.364, 0.382, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007_Material051_0.geometry}
        material={materials['Material.074_20']}
        position={[-1.244, 1.846, -3.701]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.364, 0.382, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gallerymodel_gallerymodel_0.geometry}
        material={materials['Material.074_28']}
        position={[-1.42, 1.648, 5.961]}
        rotation={[0.441, -1.284, 0.441]}
        scale={0.807}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.IOSHIELD_IOSHIELD_0.geometry}
        material={materials['Material.074_3']}
        position={[-2.597, 2.848, -4.225]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.265, 0.309, 0.318]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['maxresdefault_(1)_maxresdefault_(1)_0'].geometry}
        material={materials['Material.074_10']}
        position={[0.877, 0.836, -3.553]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.394}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['metal-mesh-500x500002_metal-mesh-500x500_0'].geometry}
        material={materials['Material.074_5']}
        position={[-2.709, 2.915, -3.353]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.796, 1.064, 0.796]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MOBOAORUSORANGETRANS_MOBOAORUSORANGETRANS_0.geometry}
        material={materials['Material.074_4']}
        position={[-2.356, 2.877, -4.239]}
        rotation={[0, 0, 0.651]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MY_SCREEN_MY_SCREEN_0.geometry}
        material={materials['Material.074_30']}
        position={[-1.362, 3.001, 3.004]}
        rotation={[-Math.PI / 2, 1.501, Math.PI / 2]}
        scale={[3.316, 3.481, 3.316]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NVIDIA_LOGO_NVIDIA_LOGO_0.geometry}
        material={materials['Material.074_12']}
        position={[0.006, 0.704, -2.891]}
        scale={0.452}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_101_Material067_0.geometry}
        material={materials['Material.074_36']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_103_Material070_0.geometry}
        material={materials['Material.074_39']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_105_Tasten_2_0.geometry}
        material={materials.Tasten_2}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_109_Material069_0.geometry}
        material={materials['Material.074_38']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_113_Material068_0.geometry}
        material={materials['Material.074_37']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_115_Material057_0.geometry}
        material={materials['Material.074_33']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_121_Material066_0.geometry}
        material={materials['Material.074_35']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_131_Material060_0.geometry}
        material={materials['Material.074_34']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_137_Material005_0.geometry}
        material={materials['Material.074_32']}
        position={[1.477, 0.326, 4.031]}
        rotation={[-Math.PI / 2, -1.481, Math.PI / 2]}
        scale={0.914}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Object_782_OnTheFly-bg_0'].geometry}
        material={materials['Material.074_40']}
        position={[1.016, 0.406, 2.44]}
        rotation={[-Math.PI / 2, 0.078, Math.PI / 2]}
        scale={0.219}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_Material053_0.geometry}
        material={materials['Material.074_21']}
        position={[1.172, 0.256, -0.292]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.244, 1.541, 1.199]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.psuback_psuback_0.geometry}
        material={materials['Material.074_13']}
        position={[-2.603, 0.78, -3.528]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.595}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['rgb-hdd-cover-aorus-v1_rgb-hdd-cover-aorus-v1_0'].geometry}
        material={materials['Material.074_9']}
        position={[-0.935, 0.832, -2.888]}
        scale={0.369}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['test-aorus-m2-souris-aorus-rgb2_test-aorus-m2-souris-aorus-rgb2'].geometry}
        material={materials['Material.074_18']}
        position={[-1.159, 1.507, -4.352]}
        scale={0.352}
      />
    </group>
  );
});

export default Wizard;
useGLTF.preload("/models/computer.glb");
